quadrantChart
    title "Функциональность и удобство использования"
    x-axis "Низкая функциональность" --> "Высокая функциональность"
    y-axis "Низкое удобство использования" --> "Высокое удобство использования"
    quadrant-1 "LinkedIn"
    quadrant-2 "HeadHunter"
    quadrant-3 "Rabota.ru"
    quadrant-4 "Indeed"
    "Glassdoor": [0.3, 0.6]
    "Наша целевая продукция": [0.8, 0.8]